AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This S3 bucket has Versioning enabled so that no data gets lost by accident.


Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
  HgServiceTagValue:
    Description: CFN tag value for the tag `hg.service`
    Type: String
  HgEnvironmentTagValue:
    Description: CFN tag value for the tag `hg.environment`
    Type: String
    AllowedValues:
      - DEV
      - TEST
      - PROD

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      Tags:
        - Key: hg.service
          Value: !Ref HgServiceTagValue
        - Key: hg.environment
          Value: !Ref HgEnvironmentTagValue
