-- for logging and debugging
select CONCAT('DATABASE=',CURRENT_DATABASE()) as col1,
CONCAT('WAREHOUSE=',CURRENT_WAREHOUSE()) as col2
;

CREATE VIEW IF NOT EXISTS open.v_heritagedb_aws_importer_listings
AS
SELECT
src:uuid::STRING AS UUID
,src:state::STRING AS STATE
,src:advertisement_id::BIGINT AS ADVERTISEMENT_ID
,src:sender_id::STRING AS SENDER_ID
,src:object_category::STRING AS OBJECT_CATEGORY
,src:object_type::INT AS OBJECT_TYPE
,src:offer_type::STRING AS OFFER_TYPE
,src:ref_property::STRING AS REF_PROPERTY
,src:ref_house::STRING AS REF_HOUSE
,src:ref_object::STRING AS REF_OBJECT
,src:object_referenz::STRING AS OBJECT_REFERENZ
,src:property_street::STRING AS PROPERTY_STREET
,src:property_place_id::BIGINT AS PROPERTY_PLACE_ID
,src:property_zip::STRING AS PROPERTY_ZIP
,src:property_additional_zip::STRING AS PROPERTY_ADDITIONAL_ZIP
,src:property_cityname::STRING AS PROPERTY_CITYNAME
,src:property_state::STRING AS PROPERTY_STATE
,src:property_country::STRING AS PROPERTY_COUNTRY
,src:property_region::STRING AS PROPERTY_REGION
,src:municipal_code::BIGINT AS MUNICIPAL_CODE
,src:situation::STRING AS SITUATION
,src:available_from::TIMESTAMP AS AVAILABLE_FROM
,src:title::STRING AS TITLE
,src:ad_description::STRING AS AD_DESCRIPTION
,src:ad_description2::STRING AS AD_DESCRIPTION2
,src:selling_price::BIGINT AS SELLING_PRICE
,src:rent_net::DECIMAL(12,2) AS RENT_NET
,src:rent_extra::DECIMAL(12,2) AS RENT_EXTRA
,src:price_unit::STRING AS PRICE_UNIT
,src:currency::STRING AS CURRENCY
,src:yield::STRING AS YIELD
,src:floor::INT AS FLOOR
,src:number_rooms::DECIMAL(5,1) AS NUMBER_ROOMS
,src:number_appartments::DECIMAL(5,1) AS NUMBER_APPARTMENTS
,src:number_floors::INT AS NUMBER_FLOORS
,src:surface_living::BIGINT AS SURFACE_LIVING
,src:surface_property::BIGINT AS SURFACE_PROPERTY
,src:surface_usable::BIGINT AS SURFACE_USABLE
,src:minimum_surface_usable::BIGINT AS MINIMUM_SURFACE_USABLE
,src:volume::BIGINT AS VOLUME
,src:year_built::BIGINT AS YEAR_BUILT
,src:year_renovated::INT AS YEAR_RENOVATED
,src:with_view::BOOLEAN AS WITH_VIEW
,src:fire_place::BOOLEAN AS FIRE_PLACE
,src:cable_tv::BOOLEAN AS CABLE_TV
,src:lift::BOOLEAN AS LIFT
,src:family::BOOLEAN AS FAMILY
,src:parking::BOOLEAN AS PARKING
,src:garage::BOOLEAN AS GARAGE
,src:balcony::BOOLEAN AS BALCONY
,src:rooffloor::BOOLEAN AS ROOFFLOOR
,src:built_new::BOOLEAN AS BUILT_NEW
,src:built_old::BOOLEAN AS BUILT_OLD
,src:corner_house::BOOLEAN AS CORNER_HOUSE
,src:gardenhouse::BOOLEAN AS GARDENHOUSE
,src:highfloor::BOOLEAN AS HIGHFLOOR
,src:middle_house::BOOLEAN AS MIDDLE_HOUSE
,src:minergy_built::BOOLEAN AS MINERGY_BUILT
,src:minergy_certified::BOOLEAN AS MINERGY_CERTIFIED
,src:plot_connected::BOOLEAN AS PLOT_CONNECTED
,src:roommate::BOOLEAN AS ROOMMATE
,src:swimmingpool::BOOLEAN AS SWIMMINGPOOL
,src:under_law::BOOLEAN AS UNDER_LAW
,src:under_roof::BOOLEAN AS UNDER_ROOF
,src:world::STRING AS WORLD
,src:distance_from_public_transport::INT AS DISTANCE_FROM_PUBLIC_TRANSPORT
,src:distance_from_shops::INT AS DISTANCE_FROM_SHOPS
,src:distance_from_kindergarten::INT AS DISTANCE_FROM_KINDERGARTEN
,src:distance_from_school::INT AS DISTANCE_FROM_SCHOOL
,src:distance_from_school2::INT AS DISTANCE_FROM_SCHOOL2
,src:pic_filename_1_small::STRING AS PIC_FILENAME_1_SMALL
,src:pic_filename_1::STRING AS PIC_FILENAME_1
,src:pic_filename_2::STRING AS PIC_FILENAME_2
,src:pic_filename_3::STRING AS PIC_FILENAME_3
,src:pic_filename_4::STRING AS PIC_FILENAME_4
,src:pic_filename_5::STRING AS PIC_FILENAME_5
,src:pic_filename_6::STRING AS PIC_FILENAME_6
,src:pic_filename_7::STRING AS PIC_FILENAME_7
,src:pic_filename_8::STRING AS PIC_FILENAME_8
,src:pic_filename_9::STRING AS PIC_FILENAME_9
,src:pic_filename_10::STRING AS PIC_FILENAME_10
,src:pic_filename_11::STRING AS PIC_FILENAME_11
,src:pic_filename_12::STRING AS PIC_FILENAME_12
,src:pic_filename_13::STRING AS PIC_FILENAME_13
,src:pic_title_1::STRING AS PIC_TITLE_1
,src:pic_title_2::STRING AS PIC_TITLE_2
,src:pic_title_3::STRING AS PIC_TITLE_3
,src:pic_title_4::STRING AS PIC_TITLE_4
,src:pic_title_5::STRING AS PIC_TITLE_5
,src:pic_title_6::STRING AS PIC_TITLE_6
,src:pic_title_7::STRING AS PIC_TITLE_7
,src:pic_title_8::STRING AS PIC_TITLE_8
,src:pic_title_9::STRING AS PIC_TITLE_9
,src:pic_title_10::STRING AS PIC_TITLE_10
,src:pic_title_11::STRING AS PIC_TITLE_11
,src:pic_title_12:STRING AS PIC_TITLE_12
,src:pic_title_13:STRING AS PIC_TITLE_13
,src:pic_description_1::STRING AS PIC_DESCRIPTION_1
,src:pic_description_2::STRING AS PIC_DESCRIPTION_2
,src:pic_description_3::STRING AS PIC_DESCRIPTION_3
,src:pic_description_4::STRING AS PIC_DESCRIPTION_4
,src:pic_description_5::STRING AS PIC_DESCRIPTION_5
,src:pic_description_6::STRING AS PIC_DESCRIPTION_6
,src:pic_description_7::STRING AS PIC_DESCRIPTION_7
,src:pic_description_8::STRING AS PIC_DESCRIPTION_8
,src:pic_description_9::STRING AS PIC_DESCRIPTION_9
,src:pic_description_10::STRING AS PIC_DESCRIPTION_10
,src:pic_description_11::STRING AS PIC_DESCRIPTION_11
,src:pic_description_12::STRING AS PIC_DESCRIPTION_12
,src:pic_description_13::STRING AS PIC_DESCRIPTION_13
,src:doc_title_1::STRING AS DOC_TITLE_1
,src:doc_description_1::STRING AS DOC_DESCRIPTION_1
,src:doc_filename_1::STRING AS DOC_FILENAME_1
,src:mov_title_1::STRING AS MOV_TITLE_1
,src:mov_description_1::STRING AS MOV_DESCRIPTION_1
,src:mov_filename_1::STRING AS MOV_FILENAME_1
,src:ad_url::STRING AS AD_URL
,src:ad_url_title::STRING AS AD_URL_TITLE
,src:object_url_deliverer::STRING AS OBJECT_URL_DELIVERER
,src:agency_id::STRING AS AGENCY_ID
,src:name::STRING AS NAME
,src:name2::STRING AS NAME2
,src:contact_person:STRING AS CONTACT_PERSON
,src:agency_street::STRING AS AGENCY_STREET
,src:agency_address_zusatz::STRING AS AGENCY_ADDRESS_ZUSATZ
,src:agency_zip::STRING AS AGENCY_ZIP
,src:agency_cityname::STRING AS AGENCY_CITYNAME
,src:agency_country::STRING AS AGENCY_COUNTRY
,src:agency_phone_day::STRING AS AGENCY_PHONE_DAY
,src:agency_mobile::STRING AS AGENCY_MOBILE
,src:agency_fax::STRING AS AGENCY_FAX
,src:agency_email::STRING AS AGENCY_EMAIL
,src:logo::STRING AS LOGO
,src:visit_name::STRING AS VISIT_NAME
,src:visit_phone::STRING AS VISIT_PHONE
,src:visit_email::STRING AS VISIT_EMAIL
,src:visit_remark::STRING AS VISIT_REMARK
,src:publish_until::TIMESTAMP AS PUBLISH_UNTIL
,src:target_destination::STRING AS TARGET_DESTINATION
,src:pers_url::STRING AS PERS_URL
,src:language_id::STRING AS LANGUAGE_ID
,src:publishing_group_id::INT AS PUBLISHING_GROUP_ID
,src:delivery_group_id::INT AS DELIVERY_GROUP_ID
,src:ad_logo::STRING AS AD_LOGO
,src:ad_logo_2::STRING AS AD_LOGO_2
,src:contact_form::STRING AS CONTACT_FORM
,src:default_contact_form_type::INT AS DEFAULT_CONTACT_FORM_TYPE
,src:application_dossier_banner::BOOLEAN AS APPLICATION_DOSSIER_BANNER
,src:person_id::BIGINT AS PERSON_ID
,src:anonymous::BOOLEAN AS ANONYMOUS
,src:distance_from_motorway::INT AS DISTANCE_FROM_MOTORWAY
,src:room_height::DECIMAL(11,2) AS ROOM_HEIGHT
,src:hall_height::DECIMAL(11,2) AS HALL_HEIGHT
,src:max_floor_loading::DECIMAL(10,1) AS MAX_FLOOR_LOADING
,src:carrying_capacity_crane::DECIMAL(10,1) AS CARRYING_CAPACITY_CRANE
,src:carrying_capacity_elevator::DECIMAL(10,1) AS CARRYING_CAPACITY_ELEVATOR
,src:isdn::BOOLEAN AS ISDN
,src:wheelchair_access::BOOLEAN AS WHEELCHAIR_ACCESS
,src:animal_allowed::BOOLEAN AS ANIMAL_ALLOWED
,src:ramp::BOOLEAN AS RAMP
,src:lifting_platform::BOOLEAN AS LIFTING_PLATFORM
,src:railway_terminal::BOOLEAN AS RAILWAY_TERMINAL
,src:restrooms::BOOLEAN AS RESTROOMS
,src:water_supply::BOOLEAN AS WATER_SUPPLY
,src:sewage_supply::BOOLEAN AS SEWAGE_SUPPLY
,src:power_supply::BOOLEAN AS POWER_SUPPLY
,src:gas_supply::BOOLEAN AS GAS_SUPPLY
,src:municipal_info::BOOLEAN AS MUNICIPAL_INFO
,src:co_ownership_numerator::BIGINT AS CO_OWNERSHIP_NUMERATOR
,src:co_ownership_denominator::BIGINT AS CO_OWNERSHIP_DENOMINATOR
,src:geak_class::STRING AS GEAK_CLASS
,src:heating_system::STRING AS HEATING_SYSTEM
,src:heating_usage_per_year::BIGINT AS HEATING_USAGE_PER_YEAR
,src:surface_living_building::BIGINT AS SURFACE_LIVING_BUILDING
,src:ekz_lower::DECIMAL(12,5) AS EKZ_LOWER
,src:ekz_upper::DECIMAL(12,5) AS EKZ_UPPER
,src:show_energy_rating::BOOLEAN AS SHOW_ENERGY_RATING
,src:hide_evalo_rating::BOOLEAN AS HIDE_EVALO_RATING
,src:energy_doc_type_1::STRING AS ENERGY_DOC_TYPE_1
,src:energy_doc_filename_1::STRING AS ENERGY_DOC_FILENAME_1
,src:energy_doc_filename_orig_1::STRING AS ENERGY_DOC_FILENAME_ORIG_1
,src:energy_doc_type_2::STRING AS ENERGY_DOC_TYPE_2
,src:energy_doc_filename_2::STRING AS ENERGY_DOC_FILENAME_2
,src:energy_doc_filename_orig_2::STRING AS ENERGY_DOC_FILENAME_ORIG_2
,src:geo_match::INT AS GEO_MATCH
,src:pool_type::INT AS POOL_TYPE
,src:agency_type::STRING AS AGENCY_TYPE
,src:created::TIMESTAMP AS CREATED
,src:search_name_ids::STRING AS SEARCH_NAME_IDS
,src:picture_count::BIGINT AS PICTURE_COUNT
,src:movie_count::BIGINT AS MOVIE_COUNT
,src:docu_count::BIGINT AS DOCU_COUNT
,src:url_count::BIGINT AS URL_COUNT
,src:geometry_lng::DECIMAL(10,7) AS GEOMETRY_LNG
,src:geometry_lat::DECIMAL(10,7) AS GEOMETRY_LAT
,src:choosetypes::STRING AS CHOOSETYPES
,src:agency_video_id::STRING AS AGENCY_VIDEO_ID
,src:timestamp::TIMESTAMP AS TIMESTAMP
,src:search_name_id_prop_country::BIGINT AS SEARCH_NAME_ID_PROP_COUNTRY
,src:search_inquiry_premium::BIGINT AS SEARCH_INQUIRY_PREMIUM
,src:search_inquiry_free::BIGINT AS SEARCH_INQUIRY_FREE
,src:search_inquiry_timestamp::TIMESTAMP AS SEARCH_INQUIRY_TIMESTAMP
,src:has_swisscom_gbit::BOOLEAN AS HAS_SWISSCOM_GBIT
,src:showcase::BOOLEAN AS SHOWCASE
,src:external_id::STRING AS EXTERNAL_ID
,src:doublette_from::STRING AS DOUBLETTE_FROM
,src:own_object_url::STRING AS OWN_OBJECT_URL
,src:publishing_ids::STRING AS PUBLISHING_IDS
,src:listing_type::STRING AS LISTING_TYPE
,src:listing_type_activate::TIMESTAMP AS LISTING_TYPE_ACTIVATE
,src:virtual_tour_url::STRING AS VIRTUAL_TOUR_URL
,src:agency_phone_day_original_number::STRING AS AGENCY_PHONE_DAY_ORIGINAL_NUMBER
,src:agency_mobile_original_number::STRING AS AGENCY_MOBILE_ORIGINAL_NUMBER
,src:visit_phone_original_number::STRING AS VISIT_PHONE_ORIGINAL_NUMBER
,src:imported_version::INT AS IMPORTED_VERSION
,src:file_modified::TIMESTAMP AS FILE_MODIFIED
,src:bundle::STRING AS BUNDLE
,src
,dt
FROM stage.heritagedb_aws_importer_listings;
