-- for logging and debugging
select CONCAT('DATABASE=',CURRENT_DATABASE()) as col1,
CONCAT('WAREHOUSE=',CURRENT_WAREHOUSE()) as col2
;

CREATE VIEW IF NOT EXISTS open.v_heritagedb_advertisement
AS
SELECT
src:advertisement_id::BIGINT AS ADVERTISEMENT_ID
,src:delivery_group_id::INTEGER AS DELIVERY_GROUP_ID
,src:publishing_group_id::INTEGER AS PUBLISHING_GROUP_ID
,src:address_id::BIGINT AS ADDRESS_ID
,src:person_id::BIGINT AS PERSON_ID
,src:ref_property::TEXT AS REF_PROPERTY
,src:ref_house::TEXT AS REF_HOUSE
,src:ref_object::TEXT AS REF_OBJECT
,src:volume::BIGINT AS VOLUME
,src:object_category::TEXT AS OBJECT_CATEGORY
,src:object_type::SMALLINT AS OBJECT_TYPE
,src:distance_from_public_transport::INTEGER AS DISTANCE_FROM_PUBLIC_TRANSPORT
,src:distance_from_shops::INTEGER AS DISTANCE_FROM_SHOPS
,src:distance_from_kindergarten::INTEGER AS DISTANCE_FROM_KINDERGARTEN
,src:distance_from_school::INTEGER AS DISTANCE_FROM_SCHOOL
,src:distance_from_school2::INTEGER AS DISTANCE_FROM_SCHOOL2
,src:publish_until::TIMESTAMPNTZ AS PUBLISH_UNTIL
,src:floor::INTEGER AS FLOOR
,src:number_rooms::NUMERIC(5,1) AS NUMBER_ROOMS
,src:number_appartments::NUMERIC(5,1) AS NUMBER_APPARTMENTS
,src:surface_living::BIGINT AS SURFACE_LIVING
,src:surface_property::BIGINT AS SURFACE_PROPERTY
,src:surface_usable::BIGINT AS SURFACE_USABLE
,src:year_built::BIGINT AS YEAR_BUILT
,src:with_view::BOOLEAN AS WITH_VIEW
,src:fire_place::BOOLEAN AS FIRE_PLACE
,src:cable_tv::BOOLEAN AS CABLE_TV
,src:lift::BOOLEAN AS LIFT
,src:family::BOOLEAN AS FAMILY
,src:parking::BOOLEAN AS PARKING
,src:garage::BOOLEAN AS GARAGE
,src:rooffloor::BOOLEAN AS ROOFFLOOR
,src:balcony::BOOLEAN AS BALCONY
,src:situation::TEXT AS SITUATION
,src:title::TEXT AS TITLE
,src:available_from::TIMESTAMPNTZ AS AVAILABLE_FROM
,src:visit_name::TEXT AS VISIT_NAME
,src:visit_phone::TEXT AS VISIT_PHONE
,src:visit_email::TEXT AS VISIT_EMAIL
,src:visit_remark::TEXT AS VISIT_REMARK
,src:ad_description::TEXT AS AD_DESCRIPTION
,src:ad_description2::TEXT AS AD_DESCRIPTION2
,src:rent_net::NUMERIC(12,2) AS RENT_NET
,src:rent_extra::NUMERIC(12,2) AS RENT_EXTRA
,src:price_unit::TEXT AS PRICE_UNIT
,src:selling_price::BIGINT AS SELLING_PRICE
,src:offer_type::TEXT AS OFFER_TYPE
,src:sender_id::TEXT AS SENDER_ID
,src:currency::TEXT AS CURRENCY
,src:yield:TEXT AS YIELD
,src:contact_person::TEXT AS CONTACT_PERSON
,src:target_destination::TEXT AS TARGET_DESTINATION
,src:data_deliverer_address_id::BIGINT AS DATA_DELIVERER_ADDRESS_ID
,src:url::TEXT AS URL
,src:timestamp::TIMESTAMPNTZ AS TIMESTAMP
,src:ad_logo::TEXT AS AD_LOGO
,src:created::TIMESTAMPNTZ AS CREATED
,src:billing_address_id::BIGINT AS BILLING_ADDRESS_ID
,src:billing_number::BIGINT AS BILLING_NUMBER
,src:distance_from_motorway::INTEGER AS DISTANCE_FROM_MOTORWAY
,src:room_height::NUMERIC(11,2) AS ROOM_HEIGHT
,src:hall_height::NUMERIC(11,2) AS HALL_HEIGHT
,src:max_floor_loading::NUMERIC(10,1) AS MAX_FLOOR_LOADING
,src:carrying_capacity_crane::NUMERIC(10,1) AS CARRYING_CAPACITY_CRANE
,src:carrying_capacity_elevator::NUMERIC(10,1) AS CARRYING_CAPACITY_ELEVATOR
,src:isdn::BOOLEAN AS ISDN
,src:wheelchair_access::BOOLEAN AS WHEELCHAIR_ACCESS
,src:animal_allowed::BOOLEAN AS ANIMAL_ALLOWED
,src:ramp::BOOLEAN AS RAMP
,src:lifting_platform::BOOLEAN AS LIFTING_PLATFORM
,src:railway_terminal::BOOLEAN AS RAILWAY_TERMINAL
,src:restrooms::BOOLEAN AS RESTROOMS
,src:water_supply::BOOLEAN AS WATER_SUPPLY
,src:sewage_supply::BOOLEAN AS SEWAGE_SUPPLY
,src:power_supply::BOOLEAN AS POWER_SUPPLY
,src:gas_supply::BOOLEAN AS GAS_SUPPLY
,src:municipal_info::BOOLEAN AS MUNICIPAL_INFO
,src:object_referenz::TEXT AS OBJECT_REFERENZ
,src:record_date::TIMESTAMPNTZ AS RECORD_DATE
,src:file_name::TEXT AS FILE_NAME
,src:file_date::TIMESTAMPNTZ AS FILE_DATE
,src:ftp_directory::TEXT AS FTP_DIRECTORY
,src:built_new::BOOLEAN AS BUILT_NEW
,src:built_old::BOOLEAN AS BUILT_OLD
,src:corner_house::BOOLEAN AS CORNER_HOUSE
,src:gardenhouse::BOOLEAN AS GARDENHOUSE
,src:highfloor::BOOLEAN AS HIGHFLOOR
,src:middle_house::BOOLEAN AS MIDDLE_HOUSE
,src:minergy_built::BOOLEAN AS MINERGY_BUILT
,src:minergy_certified::BOOLEAN AS MINERGY_CERTIFIED
,src:number_floors::SMALLINT AS NUMBER_FLOORS
,src:plot_connected::BOOLEAN AS PLOT_CONNECTED
,src:roommate::BOOLEAN AS ROOMMATE
,src:swimmingpool::BOOLEAN AS SWIMMINGPOOL
,src:under_law::BOOLEAN AS UNDER_LAW
,src:under_roof::BOOLEAN AS UNDER_ROOF
,src:world::TEXT AS WORLD
,src:year_renovated::SMALLINT AS YEAR_RENOVATED
,src:ad_logo_2::TEXT AS AD_LOGO_2
,src:ad_url_title::TEXT AS AD_URL_TITLE
,src:contact_form::TEXT AS CONTACT_FORM
,src:default_contact_form_type::SMALLINT AS DEFAULT_CONTACT_FORM_TYPE
,src:version::TEXT AS VERSION
,src:object_url_deliverer::TEXT AS OBJECT_URL_DELIVERER
,src:minimum_surface_usable::BIGINT AS MINIMUM_SURFACE_USABLE
,src:co_ownership_numerator::BIGINT AS CO_OWNERSHIP_NUMERATOR
,src:co_ownership_denominator::BIGINT AS CO_OWNERSHIP_DENOMINATOR
,src:geak_class::TEXT AS GEAK_CLASS
,src:heating_system::TEXT AS HEATING_SYSTEM
,src:heating_usage_per_year::BIGINT AS HEATING_USAGE_PER_YEAR
,src:surface_living_building::BIGINT AS SURFACE_LIVING_BUILDING
,src:ekz_lower::NUMERIC(12,5) AS EKZ_LOWER
,src:ekz_upper::NUMERIC(12,5) AS EKZ_UPPER
,src:show_energy_rating::SMALLINT AS SHOW_ENERGY_RATING
,src:hide_evalo_rating::SMALLINT AS HIDE_EVALO_RATING
,src:energy_doc_type_1::TEXT AS ENERGY_DOC_TYPE_1
,src:energy_doc_filename_1::TEXT AS ENERGY_DOC_FILENAME_1
,src:energy_doc_filename_orig_1::TEXT AS ENERGY_DOC_FILENAME_ORIG_1
,src:energy_doc_type_2::TEXT AS ENERGY_DOC_TYPE_2
,src:energy_doc_filename_2::TEXT AS ENERGY_DOC_FILENAME_2
,src:energy_doc_filename_orig_2::TEXT AS ENERGY_DOC_FILENAME_ORIG_2
,src:showcase::BOOLEAN AS SHOWCASE
,src:listing_type::TEXT AS LISTING_TYPE
,src:listing_type_activate::TIMESTAMPNTZ AS LISTING_TYPE_ACTIVATE
,src:virtual_tour_url::TEXT AS VIRTUAL_TOUR_URL
,src
,dt
FROM stage.heritagedb_advertisement;
