-- for logging and debugging
select CONCAT('DATABASE=',CURRENT_DATABASE()) as col1,
CONCAT('WAREHOUSE=',CURRENT_WAREHOUSE()) as col2
;

CREATE VIEW IF NOT EXISTS open.v_heritagedb_online_publishing_desktop
AS
SELECT
src:online_publishing_desktop_id::BIGINT AS ONLINE_PUBLISHING_DESKTOP_ID
,src:agency_id::STRING AS AGENCY_ID
,src:ref_property::STRING AS REF_PROPERTY
,src:ref_house::STRING AS REF_HOUSE
,src:ref_object::STRING AS REF_OBJECT
,src:world::STRING AS WORLD
,src:volume::BIGINT AS VOLUME
,src:object_category::STRING AS OBJECT_CATEGORY
,src:object_type::INT AS OBJECT_TYPE
,src:object_art::STRING AS OBJECT_ART
,src:distance_from_public_transport::INT AS DISTANCE_FROM_PUBLIC_TRANSPORT
,src:distance_from_shops::INT AS DISTANCE_FROM_SHOPS
,src:distance_from_kindergarten::INT AS DISTANCE_FROM_KINDERGARTEN
,src:distance_from_school::INT AS DISTANCE_FROM_SCHOOL
,src:distance_from_school2::INT AS DISTANCE_FROM_SCHOOL2
,src:distance_from_motorway::INT AS DISTANCE_FROM_MOTORWAY
,src:publish_until::TIMESTAMP AS PUBLISH_UNTIL
,src:floor::INT AS FLOOR
,src:number_rooms::DECIMAL(5,1) AS NUMBER_ROOMS
,src:number_floors::INT AS NUMBER_FLOORS
,src:number_appartments::DECIMAL(5,1) AS NUMBER_APPARTMENTS
,src:surface_living::BIGINT AS SURFACE_LIVING
,src:surface_property::BIGINT AS SURFACE_PROPERTY
,src:surface_usable::BIGINT AS SURFACE_USABLE
,src:room_height::DECIMAL(11,2) AS ROOM_HEIGHT
,src:hall_height::DECIMAL(11,2) AS HALL_HEIGHT
,src:max_floor_loading::DECIMAL(10,1) AS MAX_FLOOR_LOADING
,src:carrying_capacity_crane::DECIMAL(10,1) AS CARRYING_CAPACITY_CRANE
,src:carrying_capacity_elevator::DECIMAL(10,1) AS CARRYING_CAPACITY_ELEVATOR
,src:year_built::BIGINT AS YEAR_BUILT
,src:year_renovated::INT AS YEAR_RENOVATED
,src:with_view::BOOLEAN AS WITH_VIEW
,src:fire_place::BOOLEAN AS FIRE_PLACE
,src:cable_tv::BOOLEAN AS CABLE_TV
,src:isdn::BOOLEAN AS ISDN
,src:lift::BOOLEAN AS LIFT
,src:wheelchair_access::BOOLEAN AS WHEELCHAIR_ACCESS
,src:animal_allowed::BOOLEAN AS ANIMAL_ALLOWED
,src:family::BOOLEAN AS FAMILY
,src:parking::BOOLEAN AS PARKING
,src:garage::BOOLEAN AS GARAGE
,src:rooffloor::BOOLEAN AS ROOFFLOOR
,src:balcony::BOOLEAN AS BALCONY
,src:ramp::BOOLEAN AS RAMP
,src:lifting_platform::BOOLEAN AS LIFTING_PLATFORM
,src:railway_terminal::BOOLEAN AS RAILWAY_TERMINAL
,src:restrooms::BOOLEAN AS RESTROOMS
,src:water_supply::BOOLEAN AS WATER_SUPPLY
,src:sewage_supply::BOOLEAN AS SEWAGE_SUPPLY
,src:power_supply::BOOLEAN AS POWER_SUPPLY
,src:gas_supply::BOOLEAN AS GAS_SUPPLY
,src:municipal_info::BOOLEAN AS MUNICIPAL_INFO
,src:roommate::BOOLEAN AS ROOMMATE
,src:corner_house::BOOLEAN AS CORNER_HOUSE
,src:middle_house::BOOLEAN AS MIDDLE_HOUSE
,src:plot_connected::BOOLEAN AS PLOT_CONNECTED
,src:gardenhouse::BOOLEAN AS GARDENHOUSE
,src:highfloor::BOOLEAN AS HIGHFLOOR
,src:built_new::BOOLEAN AS BUILT_NEW
,src:built_old::BOOLEAN AS BUILT_OLD
,src:under_law::BOOLEAN AS UNDER_LAW
,src:under_roof::BOOLEAN AS UNDER_ROOF
,src:situation::STRING AS SITUATION
,src:title::STRING AS TITLE
,src:available_from::TIMESTAMP AS AVAILABLE_FROM
,src:visit_name::STRING AS VISIT_NAME
,src:visit_phone::STRING AS VISIT_PHONE
,src:visit_email::STRING AS VISIT_EMAIL
,src:visit_remark::STRING AS VISIT_REMARK
,src:contact_title::STRING AS CONTACT_TITLE
,src:contact_name::STRING AS CONTACT_NAME
,src:contact_lastname::STRING AS CONTACT_LASTNAME
,src:contact_firm_name::STRING AS CONTACT_FIRM_NAME
,src:contact_phone_private::STRING AS CONTACT_PHONE_PRIVATE
,src:contact_phone_business::STRING AS CONTACT_PHONE_BUSINESS
,src:contact_mobile::STRING AS CONTACT_MOBILE
,src:contact_email::STRING AS CONTACT_EMAIL
,src:ad_description::STRING AS AD_DESCRIPTION
,src:ad_description2::STRING AS AD_DESCRIPTION2
,src:rent_net::DECIMAL(12,2) AS RENT_NET
,src:rent_extra::DECIMAL(12,2) AS RENT_EXTRA
,src:price_unit::STRING AS PRICE_UNIT
,src:selling_price::BIGINT AS SELLING_PRICE
,src:offer_type::STRING AS OFFER_TYPE
,src:sender_id::STRING AS SENDER_ID
,src:currency::STRING AS CURRENCY
,src:yield::STRING AS YIELD
,src:target_destination::STRING AS TARGET_DESTINATION
,src:ad_url::STRING AS AD_URL
,src:deliver_address_type::STRING AS DELIVER_ADDRESS_TYPE
,src:deliver_person_id::BIGINT AS DELIVER_PERSON_ID
,src:deliver_name::STRING AS DELIVER_NAME
,src:deliver_name2::STRING AS DELIVER_NAME2
,src:deliver_vorname::STRING AS DELIVER_VORNAME
,src:deliver_street::STRING AS DELIVER_STREET
,src:deliver_place_id::BIGINT AS DELIVER_PLACE_ID
,src:deliver_state::STRING AS DELIVER_STATE
,src:deliver_country::STRING AS DELIVER_COUNTRY
,src:deliver_region::STRING AS DELIVER_REGION
,src:deliver_fax::STRING AS DELIVER_FAX
,src:deliver_phone_day::STRING AS DELIVER_PHONE_DAY
,src:deliver_phone_evening::STRING AS DELIVER_PHONE_EVENING
,src:deliver_mobile::STRING AS DELIVER_MOBILE
,src:deliver_email::STRING AS DELIVER_EMAIL
,src:property_address_type::STRING AS PROPERTY_ADDRESS_TYPE
,src:property_person_id::BIGINT AS PROPERTY_PERSON_ID
,src:property_name::STRING AS PROPERTY_NAME
,src:property_name2::STRING AS PROPERTY_NAME2
,src:property_vorname::STRING AS PROPERTY_VORNAME
,src:property_street::STRING AS PROPERTY_STREET
,src:property_place_id::BIGINT AS PROPERTY_PLACE_ID
,src:property_cityname::STRING AS PROPERTY_CITYNAME
,src:property_zip::STRING AS PROPERTY_ZIP
,src:property_state::STRING AS PROPERTY_STATE
,src:property_country::STRING AS PROPERTY_COUNTRY
,src:property_region::STRING AS PROPERTY_REGION
,src:property_fax::STRING AS PROPERTY_FAX
,src:property_phone_day::STRING AS PROPERTY_PHONE_DAY
,src:property_evening::STRING AS PROPERTY_EVENING
,src:property_mobile::STRING AS PROPERTY_MOBILE
,src:property_email::STRING AS PROPERTY_EMAIL
,src:billing_address_type::STRING AS BILLING_ADDRESS_TYPE
,src:billing_person_id::BIGINT AS BILLING_PERSON_ID
,src:billing_name::STRING AS BILLING_NAME
,src:billing_name2::STRING AS BILLING_NAME2
,src:billing_vorname::STRING AS BILLING_VORNAME
,src:billing_street::STRING AS BILLING_STREET
,src:billing_state::STRING AS BILLING_STATE
,src:billing_country::STRING AS BILLING_COUNTRY
,src:billing_region::STRING AS BILLING_REGION
,src:billing_fax::STRING AS BILLING_FAX
,src:billing_phone_day::STRING AS BILLING_PHONE_DAY
,src:billing_phone_evening::STRING AS BILLING_PHONE_EVENING
,src:billing_mobile::STRING AS BILLING_MOBILE
,src:billing_email::STRING AS BILLING_EMAIL
,src:billing_anrede::STRING AS BILLING_ANREDE
,src:billing_city::STRING AS BILLING_CITY
,src:billing_po_box::STRING AS BILLING_PO_BOX
,src:billing_zip::STRING AS BILLING_ZIP
,src:credit_card_company::STRING AS CREDIT_CARD_COMPANY
,src:credit_card_number::BIGINT AS CREDIT_CARD_NUMBER
,src:credit_card_name::STRING AS CREDIT_CARD_NAME
,src:credit_card_valid_until::TIMESTAMP AS CREDIT_CARD_VALID_UNTIL
,src:publishing_group_id::INT AS PUBLISHING_GROUP_ID
,src:delivery_group_id::INT AS DELIVERY_GROUP_ID
,src:agency_ref::STRING AS AGENCY_REF
,src:person_id::BIGINT AS PERSON_ID
,src:pic_title_1::STRING AS PIC_TITLE_1
,src:pic_description_1::STRING AS PIC_DESCRIPTION_1
,src:pic_filename_1::STRING AS PIC_FILENAME_1
,src:pic_filename_orig_1::STRING AS PIC_FILENAME_ORIG_1
,src:pic_photo_plan_1::BOOLEAN AS PIC_PHOTO_PLAN_1
,src:pic_title_2::STRING AS PIC_TITLE_2
,src:pic_description_2::STRING AS PIC_DESCRIPTION_2
,src:pic_filename_2::STRING AS PIC_FILENAME_2
,src:pic_filename_orig_2::STRING AS PIC_FILENAME_ORIG_2
,src:pic_photo_plan_2::BOOLEAN AS PIC_PHOTO_PLAN_2
,src:pic_title_3::STRING AS PIC_TITLE_3
,src:pic_description_3::STRING AS PIC_DESCRIPTION_3
,src:pic_filename_3::STRING AS PIC_FILENAME_3
,src:pic_filename_orig_3::STRING AS PIC_FILENAME_ORIG_3
,src:pic_photo_plan_3::BOOLEAN AS PIC_PHOTO_PLAN_3
,src:pic_title_4::STRING AS PIC_TITLE_4
,src:pic_description_4::STRING AS PIC_DESCRIPTION_4
,src:pic_filename_4::STRING AS PIC_FILENAME_4
,src:pic_filename_orig_4::STRING AS PIC_FILENAME_ORIG_4
,src:pic_photo_plan_4::BOOLEAN AS PIC_PHOTO_PLAN_4
,src:pic_title_5::STRING AS PIC_TITLE_5
,src:pic_description_5::STRING AS PIC_DESCRIPTION_5
,src:pic_filename_5::STRING AS PIC_FILENAME_5
,src:pic_filename_orig_5::STRING AS PIC_FILENAME_ORIG_5
,src:pic_photo_plan_5::BOOLEAN AS PIC_PHOTO_PLAN_5
,src:pic_title_6::STRING AS PIC_TITLE_6
,src:pic_description_6::STRING AS PIC_DESCRIPTION_6
,src:pic_filename_6::STRING AS PIC_FILENAME_6
,src:pic_filename_orig_6::STRING AS PIC_FILENAME_ORIG_6
,src:pic_photo_plan_6::BOOLEAN AS PIC_PHOTO_PLAN_6
,src:pic_title_7::STRING AS PIC_TITLE_7
,src:pic_description_7::STRING AS PIC_DESCRIPTION_7
,src:pic_filename_7::STRING AS PIC_FILENAME_7
,src:pic_filename_orig_7::STRING AS PIC_FILENAME_ORIG_7
,src:pic_photo_plan_7::BOOLEAN AS PIC_PHOTO_PLAN_7
,src:pic_title_8::STRING AS PIC_TITLE_8
,src:pic_description_8::STRING AS PIC_DESCRIPTION_8
,src:pic_filename_8::STRING AS PIC_FILENAME_8
,src:pic_filename_orig_8::STRING AS PIC_FILENAME_ORIG_8
,src:pic_photo_plan_8::BOOLEAN AS PIC_PHOTO_PLAN_8
,src:pic_title_9::STRING AS PIC_TITLE_9
,src:pic_description_9::STRING AS PIC_DESCRIPTION_9
,src:pic_filename_9::STRING AS PIC_FILENAME_9
,src:pic_filename_orig_9::STRING AS PIC_FILENAME_ORIG_9
,src:pic_photo_plan_9::BOOLEAN AS PIC_PHOTO_PLAN_9
,src:pic_title_10::STRING AS PIC_TITLE_10
,src:pic_description_10::STRING AS PIC_DESCRIPTION_10
,src:pic_filename_10::STRING AS PIC_FILENAME_10
,src:pic_filename_orig_10::STRING AS PIC_FILENAME_ORIG_10
,src:pic_photo_plan_10::BOOLEAN AS PIC_PHOTO_PLAN_10
,src:pic_title_11::STRING AS PIC_TITLE_11
,src:pic_description_11::STRING AS PIC_DESCRIPTION_11
,src:pic_filename_11::STRING AS PIC_FILENAME_11
,src:pic_filename_orig_11::STRING AS PIC_FILENAME_ORIG_11
,src:pic_photo_plan_11::BOOLEAN AS PIC_PHOTO_PLAN_11
,src:pic_title_12::STRING AS PIC_TITLE_12
,src:pic_description_12::STRING AS PIC_DESCRIPTION_12
,src:pic_filename_12::STRING AS PIC_FILENAME_12
,src:pic_filename_orig_12::STRING AS PIC_FILENAME_ORIG_12
,src:pic_photo_plan_12::BOOLEAN AS PIC_PHOTO_PLAN_12
,src:pic_title_13::STRING AS PIC_TITLE_13
,src:pic_description_13::STRING AS PIC_DESCRIPTION_13
,src:pic_filename_13::STRING AS PIC_FILENAME_13
,src:pic_filename_orig_13::STRING AS PIC_FILENAME_ORIG_13
,src:pic_photo_plan_13::BOOLEAN AS PIC_PHOTO_PLAN_13
,src:doc_title_1::STRING AS DOC_TITLE_1
,src:doc_description_1::STRING AS DOC_DESCRIPTION_1
,src:doc_filename_1::STRING AS DOC_FILENAME_1
,src:doc_filename_orig_1::STRING AS DOC_FILENAME_ORIG_1
,src:mov_title_1::STRING AS MOV_TITLE_1
,src:mov_description_1::STRING AS MOV_DESCRIPTION_1
,src:mov_filename_1::STRING AS MOV_FILENAME_1
,src:mov_filename_orig_1::STRING AS MOV_FILENAME_ORIG_1
,src:time_stamp::TIMESTAMP AS TIME_STAMP
,src:ad_logo::STRING AS AD_LOGO
,src:ad_logo_2::STRING AS AD_LOGO_2
,src:online_person_id::BIGINT AS ONLINE_PERSON_ID
,src:status::STRING AS STATUS
,src:object_referenz::STRING AS OBJECT_REFERENZ
,src:combi_publishing_group_id::INT AS COMBI_PUBLISHING_GROUP_ID
,src:billing_language_id::STRING AS BILLING_LANGUAGE_ID
,src:pricing::BIGINT AS PRICING
,src:extra_effort::DECIMAL(10,2) AS EXTRA_EFFORT
,src:extra_effort_date::TIMESTAMP AS EXTRA_EFFORT_DATE
,src:deliver_cityname::STRING AS DELIVER_CITYNAME
,src:deliver_zip::STRING AS DELIVER_ZIP
,src:swimmingpool::BOOLEAN AS SWIMMINGPOOL
,src:minergy_built::BOOLEAN AS MINERGY_BUILT
,src:minergy_certified::BOOLEAN AS MINERGY_CERTIFIED
,src:created::TIMESTAMP AS CREATED
,src:form_combination::STRING AS FORM_COMBINATION
,src:deliver_address_zusatz::STRING AS DELIVER_ADDRESS_ZUSATZ
,src:billing_place_id::BIGINT AS BILLING_PLACE_ID
,src:billing_firm_name::STRING AS BILLING_FIRM_NAME
,src:ad_url_title::STRING AS AD_URL_TITLE
,src:marked_until::TIMESTAMP AS MARKED_UNTIL
,src:coupon_id::STRING AS COUPON_ID
,src:geo_match::INT AS GEO_MATCH
,src:contact_form::STRING AS CONTACT_FORM
,src:default_contact_form_type::INT AS DEFAULT_CONTACT_FORM_TYPE
,src:submitter_ip_address::STRING AS SUBMITTER_IP_ADDRESS
,src:submitter_country_code::STRING AS SUBMITTER_COUNTRY_CODE
,src:submitter_country_name::STRING AS SUBMITTER_COUNTRY_NAME
,src:last_changed_by::STRING AS LAST_CHANGED_BY
,src:object_referenz_copied_from::STRING AS OBJECT_REFERENZ_COPIED_FROM
,src:version::STRING AS VERSION
,src:deliver_to_newhome_start::TIMESTAMP AS DELIVER_TO_NEWHOME_START
,src:deliver_to_newhome_end::TIMESTAMP AS DELIVER_TO_NEWHOME_END
,src:minimum_surface_usable::BIGINT AS MINIMUM_SURFACE_USABLE
,src:invoice_delivery_type::INT AS INVOICE_DELIVERY_TYPE
,src:geometry_lat::DECIMAL(10,7) AS GEOMETRY_LAT
,src:geometry_lng::DECIMAL(10,7) AS GEOMETRY_LNG
,src:platform::STRING AS PLATFORM
,src:upgrade_raiffeisen_to_homegate::INT AS UPGRADE_RAIFFEISEN_TO_HOMEGATE
,src:delete_reason::STRING AS DELETE_REASON
,src:co_ownership_numerator::BIGINT AS CO_OWNERSHIP_NUMERATOR
,src:co_ownership_denominator::BIGINT AS CO_OWNERSHIP_DENOMINATOR
,src:geak_class::STRING AS GEAK_CLASS
,src:heating_system::STRING AS HEATING_SYSTEM
,src:heating_usage_per_year::BIGINT AS HEATING_USAGE_PER_YEAR
,src:surface_living_building::BIGINT AS SURFACE_LIVING_BUILDING
,src:ekz_lower::DECIMAL(12,5) AS EKZ_LOWER
,src:ekz_upper::DECIMAL(12,5) AS EKZ_UPPER
,src:show_energy_rating::BOOLEAN AS SHOW_ENERGY_RATING
,src:hide_evalo_rating::BOOLEAN AS HIDE_EVALO_RATING
,src:energy_doc_type_1::STRING AS ENERGY_DOC_TYPE_1
,src:energy_doc_filename_1::STRING AS ENERGY_DOC_FILENAME_1
,src:energy_doc_filename_orig_1::STRING AS ENERGY_DOC_FILENAME_ORIG_1
,src:energy_doc_type_2::STRING AS ENERGY_DOC_TYPE_2
,src:energy_doc_filename_2::STRING AS ENERGY_DOC_FILENAME_2
,src:energy_doc_filename_orig_2::STRING AS ENERGY_DOC_FILENAME_ORIG_2
,src:billing_price::DECIMAL(38,18) AS BILLING_PRICE
,src:last_extend_duration::INT AS LAST_EXTEND_DURATION
,src:listing_type::STRING AS LISTING_TYPE
,src:listing_type_activate::TIMESTAMP AS LISTING_TYPE_ACTIVATE
,src:virtual_tour_url::STRING AS VIRTUAL_TOUR_URL
,src:auto_approved::BOOLEAN AS AUTO_APPROVED
,src:bundle::STRING AS BUNDLE
,src
,dt
FROM stage.heritagedb_online_publishing_desktop;
